name: Publish to Image Registry

on:
  push:
    branches:
      - ubicloud-runner
    
jobs:
  build_arm64:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, ubicloud-standard-2, ubicloud-standard-16, ubicloud-standard-2-arm, ubicloud-standard-16-arm]
    continue-on-error: true
    name: ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    timeout-minutes: 300
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: supabase/studio
          flavor: latest=false
          tags: type=raw,value=${{matrix.runs-on}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - id: build
        uses: docker/build-push-action@v3
        with:
          push: false
          context: '{{defaultContext}}'
          file: apps/studio/Dockerfile
          target: production
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
