name: Check code with TypeScript

on:
  push:
    branches:
      # - 'master'
      - 'build-test'

# Cancel old builds on new commit for same workflow + branch/PR
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

jobs:
  typecheck:
    # Uses larger hosted runner as it significantly decreases build times
    # runs-on: [larger-runner-4cpu]
    strategy:
      matrix:
        runs-on: [ubuntu-latest, ubicloud-standard-2, ubicloud-standard-4, ubicloud-standard-8, ubicloud-standard-16]
    name: Typecheck ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    # strategy:
    #   matrix:
    #     node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run TypeScript type check
        run: npx turbo run typecheck
